apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
  name: operator.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: Flow is the Schema for the flows API
      displayName: Flow
      kind: Flow
      name: flows.sample.tadayosi.github.io
      version: v1alpha1
    - description: Hello is the Schema for the hellos API
      displayName: Hello
      kind: Hello
      name: hellos.sample.tadayosi.github.io
      version: v1alpha1
  description: Sample Operator
  displayName: Sample Operator
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - sample
  links:
  - name: Operator
    url: https://operator.domain
  maturity: alpha
  provider:
    name: Tadayoshi Sato
  version: 0.0.0
